### ISSUE TITLE
not working on eslint: "^4.16.0"

### ISSUE THREAD

**Issue by marcelmokos** [erikdesjardins/eslint-plugin-dollar-sign#11]
Error: Failed to load plugin dollar-sign: Cannot find module 'eslint-plugin-dollar-sign'

.eslint.yml

```yml
---
extends:
  - airbnb-base/legacy
  - prettier

env:
  amd: true
  browser: true
  jasmine: true
  jquery: true
  es6: false

parserOptions:
  ecmaVersion: 5
  ecmaFeatures:
    globalReturn: false

plugins:
  - import
  - prettier
  - dollar-sign

rules:
  dollar-sign/dollar-sign:
    - error
    - ignoreProperties
```
